name: 'docker publish'
on:
  push:
    branches:
      - 'main'

jobs:
  bookstore-gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: '.'
    steps:
      - name: 'set timestamp'
        id: timestamp
        run: echo "::set-output name=timestamp::$(date '+%Y%m%d%H%M%S')"
      - name: 'build and push'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/bmonish/test-docker-push:${{steps.timestamp.outputs.timestamp}}
